### ISSUE TITLE
I disabled the google two step auth and it still comes up?

### ISSUE THREAD

**Issue by soundcode024** [google/google-authenticator-android#76] opened 2018-02-06 22:22 UTC

**Comment by soundcode024** [comment] 2018-02-06 22:26
So i disabled the google auth and when i log in from a new location it still comes up, i dont like the idea of google putting things on my screen on top of other apps even after disabling it. 

Is there a way to completely block this?

**Comment by ThomasHabets** [comment] 2018-02-06 22:28
Need many more details, including screenshots or something. I don't know what you say you did and what happens.

**Comment by soundcode024** [comment] 2018-02-12 02:56
![screenshot_4](https://user-images.githubusercontent.com/36211175/36082200-1d81f7c6-0f9f-11e8-9889-80df80e936bf.png)
![screenshot_20180212-025625](https://user-images.githubusercontent.com/36211175/36082322-571256f6-0fa0-11e8-9915-6e5d48fb699f.png)
![screenshot_1](https://user-images.githubusercontent.com/36211175/36082323-58f2aa8e-0fa0-11e8-8033-1c3ce091a786.png)

**Comment by ThomasHabets** [comment] 2018-02-12 14:05
You're stating what's happening, but not what the problem is.

In any case this appears to be a support request for a Google account, not about Google authenticator. So closing.

**Closed by ThomasHabets** 2018-02-12 14:05 UTC
Labels: question
