### ISSUE TITLE
2-step enabled, can't authorize Authenticator

### ISSUE THREAD

**Issue by bluesquall** [google/google-authenticator-android#7] opened 2015-02-13 15:53 UTC
Reopened from [Issue 411](https://github.com/google/google-authenticator/issues/411) under [google-authenticator](https://github.com/google/google-authenticator) (which was closed because that repo is apparently not for the android version anymore...)

> Original issue 412 created by nick.krabbenhoeft on 2014-07-30T06:30:03.000Z:
> 
> What steps will reproduce the problem?
> 1. I enabled 2-step verification for a Google Apps for Non-Profits account. It works
> 2. I go to my phone's Authenticator which I use with my Gmail account, and try to add the Google Apps account
> 3. Error, "Continue on a computer."
> 
> What is the expected output? What do you see instead?
> I expect a new account to be added. I receive instructions to "To enable 2-step verifcation, visit accounts.google.com/security..."
> 
> What version of the product are you using? On what operating system?
> Authenticator 2.49 on Android 4.4.2
> 
> Please provide any additional information below.
> I've tried disabling and re-enabling 2-step to know effect.

**Comment by ThomasHabets** [comment] 2015-02-13 15:57
Please provide more detailed steps for 2 and 3. What exactly did you click on? What exactly happened?

What should work is:
1) Open GA
2) Click tripple-dot menu at upper right
3) Click "Set up account"
4) Scan a barcode
5) Point phone to barcode website provides.

**Comment by bluesquall** [comment] 2015-02-13 16:10
At least in my case, this was a situation where I was moving to a new phone.

To do that, you apparently need to start from the web interface on a computer -- it doesn't look like the app supports it. The instructions given by the app are misleading, and only make sense if you haven't already enabled 2-step verification.

1. Go to [accounts.google.com/security](accounts.google.com/security)
2. Click on [2-Step Verification](https://accounts.google.com/b/0/SmsAuthConfig)
    - You will have to re-authenticate -- hope you still have the first phone or can have Google send you a  SMS.
3. Under the *Verification codes* tab, there will be a header for *PRIMARY WAY YOU RECEIVE CODES*. In the block of text below, there is a link to _move to a different phone_. Follow the instructions for that link.
4. Instead of trying to add the Google apps account listed in the Authenticator app on your phone, you will need to scan the QR code on your screen.

I'd suggest changing the help message in the app from:

> To enable 2-step verifcation, visit accounts.google.com/security...

to:

> To enable 2-step verifcation, visit accounts.google.com/security. If 2-step verification is already enabled on your account, visit accounts.google.com/b/0/SmsAuthSettings and follow the link to "move to a different phone", then scan the QR code with this phone when prompted.

**Comment by ThomasHabets** [comment] 2015-02-13 18:08
Where are you seeing this message? I clicked around a bit and couldn't find it, and it doesn't seem to be in the source code.

**Comment by dpippenger** [comment] 2015-02-13 19:33
I'm experiencing this issue as well. I'm running android 4.4.2 and authenticator 2.49. I also have a nexus 5 running 5.0.1. 

When inputting the same token seed to both phones the 4.4.2 device never generates the correct codes, while the 5.0.1 device using the same seed generates the proper codes.

I've also tried inputting the tokens using QR codes to eliminate the chance of user input error. I've confirmed the token codes are wrong for multiple sites including github, gmail, aws, several online games. The software is just completely unusable on the 4.4.2 platform right now.

My handset hardware is a Blu studio energy in the event that's related to this bug.

**Comment by ThomasHabets** [comment] 2015-02-13 19:41
Are you sure you're commenting on the right bug? That seems completely unrelated to me.

**Comment by dpippenger** [comment] 2015-02-13 19:46
My assumption was you couldn't authenticate due to bad codes. If that's not the case I'll open a new bug.

**Comment by ThomasHabets** [comment] 2015-02-13 19:47
This bug is about problems adding new accounts, not using its codes.

**Comment by dpippenger** [comment] 2015-02-13 19:50
Sorry, it’s difficult to track since it’s been moved around to 3 different bug trackers. I’ll create a new bug.

David Pippenger
Cloud DevOps Engineer
Phone: 213-253-8513

On Feb 13, 2015, at 11:47 AM, Thomas Habets <notifications@github.com<mailto:notifications@github.com>> wrote:


This bug is about problems adding new accounts, not using its codes.

**Comment by ThomasHabets** [comment] 2015-02-24 18:46
Where are you seeing this message in the app, exactly? I can't find it.

**Comment by ndthuan** [comment] 2015-03-02 03:21
Hello,

I have the same issue on my Android 4.4. It was and is still working fine on another phone of mine which is running with Android 4.2.

My steps:
- Go to 2-Step Verification settings screen
- Click on "Move to a different phone"
- Choose Android
- Scan the barcode printed on the screen
- Enter the code generated by the app, click on "Verify and Save", got "The code is incorrect. Try again."
- Wait for 1 minute, enter another code, got "The code is incorrect. Try again.
Tip: Codes are time-dependent. Make sure your phone is set to the correct local time."

I tried to sync time on the app but it still doesn't work.

**Comment by ThomasHabets** [comment] 2015-03-02 17:28
You're not saying where you are seeing this message, but it sounds like this is all stuff you see on the web. This bug tracker is about the OpenSource Android Google Authenticator, not support for Google services in general.

**Comment by ndthuan** [comment] 2015-03-03 14:08
Yes, those error messages are on Google web. The thing is that the generated code works on my other phone.

**Comment by ThomasHabets** [comment] 2015-03-03 17:30
Could you clarify how these two issues are the same? They seems to be describing different failures.

ndthuan: If it works on one phone and not another after scanning the same code, that may be issue #4. 

bluesquail: My question above is still open.

**Comment by ThomasHabets** [comment] 2015-03-30 10:27
This issue doesn't seem to be related to Google Authenticator, and reporter is not responding. Closing.

**Closed by ThomasHabets** 2015-03-30 10:27 UTC

**Comment by sarrala** [comment] 2015-07-16 22:06
exactly same issue here. Hints on this thread helped to solve it.

It's all about ambiguous instructions when you're moving from old device to new on.

@thomashabets you can just read issue descriptions again and only consider op's @bluesquall comments as helpful ones as @ndthuan seems to be talking about another issue only related to web pages.

**Comment by ocdtrekkie** [comment] 2015-07-17 00:38
@sarrala This doesn't pertain to the open source version (hosted here on Github). Bluesquall indicated it was version 2.49, which is a closed source version from the Play Store.

**Comment by ThomasHabets** [comment] 2015-07-17 08:23
@sarrala description is too unclear to see if it refers to google account problems or the GA app. If the latter then *maybe* it's also applicable to the open source version (this project) and therefore should be fixed here too. But the error messages given in the description do not appear to be anywhere in the code, and I can't find it in the closed source app UI, so I think it's not the app.

**Comment by sarrala** [comment] 2015-07-17 17:29
@ThomasHabets App displays dialog window askin you to enable 2-step auth feature through web interface. 

Take a look at screenshots @ drive: 

https://drive.google.com/folder/d/0BxFEnbBJ55iPb185VnE2bDMyaVk/edit

Selected account does have 2-way auth activated.

Maybe you could confirm if same thing would happen here.

**Comment by ThomasHabets** [comment] 2015-09-03 13:16
I don't know where this message comes  from. It could come from the web or the closed source app. It's not from this project as far as I can see, at least.

Either way, this bug doesn't contain clear steps on how to reproduce the problem.

**Comment by sarrala** [comment] 2015-09-03 19:36
@ThomasHabets in my case (when I took screenshots) message came from google's authenticator app version 2.49 (com.google.android.apps.authenticator2).

I see that this repository contains version 2.21 so I think that this message box was added afterwards and is only present on apk distributed by google through their play store.

**Comment by Corwin7** [comment] 2015-10-13 18:51
Sounds like the same issue here. I scan the QR code, get a number, put it in the "Code: " box and get a response of "The code is incorrect. Try again". I have Android 4.4.2 and Google Authenticator 2.49.

**Comment by GildedHonour** [comment] 2015-10-16 16:10
Is it possible to use GA for the same google account on 2 different android devices?

**Comment by ocdtrekkie** [comment] 2015-10-16 16:12
@GildedHonour Yup. Scan the barcode on both devices at the same time. (Or save the barcode.) Google just doesn't let you access the same barcode at a later date for security reasons.

**Comment by GildedHonour** [comment] 2015-10-16 16:15
I couldn't because I got the same issue as in the 1st message, it said  "enable 2 step vef-on", but it had been already enabled and GA set up on my another android device.

**Comment by ocdtrekkie** [comment] 2015-10-16 16:49
You cannot ADD a second device. You have to set up 2-step on both devices at once. I'd recommend removing 2-step from your Google Account and then re-adding it while you have both devices in front of you.

**Comment by ocdtrekkie** [comment] 2015-10-16 16:50
Disclaimer though: I've never used the newer closed source version of Google Authenticator. They may or may not have added something that breaks this ability.
