### ISSUE TITLE
Authenticator produces wrong codes during setup of new entries

### ISSUE THREAD

**Issue by MarMuc** [google/google-authenticator-android#3] opened 2014-12-26 09:45 UTC
**What steps will reproduce the problem?**
 1. Go to auth setup page (Google, Amazon AWS, ...)
 2. Scan code or enter code manually
 3. New entry added to Authenticator
 4. Codes wont be accepted to verify Authenticator ("Wrong code. Please try again"

**What is the expected output? What do you see instead?**
 Not able to use Authenticator as "connection" wont be verified.

**What version of the product are you using? On what operating system?**
 Authenticator v2.49 on Android 4.4.2 (latest available for my phone [Wiko Highway Signs])

**Please provide any additional information below.**
 Never had any problems with the Authenticator on my old phone (Samsung Galaxy S).
 Disabled 2-step auth properly before trying to add the auth on the new phone.
 Setting up auth does not work with any "provider" (Google, Amazon AWS, ...).
 I did sync the time in Authenticator (No update required, time already syncronised); I re-installed Authenticator; I rebooter the phone; I uninstalled Authenticator, rebootet the phone, installed Authenticator again; nothing helped.

Thanks for your help!

**Comment by rtitlestad** [comment] 2015-01-03 09:00
This issue might be the same as the one which pull request #4 fixes since the Wiko Highway Signs also has a MediaTek chipset. You could try again now that the fix has been merged.

**Comment by MarMuc** [comment] 2015-01-06 09:04
Thanks for your note.
Is there a new, fixed version available which is compiled and ready to be installed on my mobile phone or do I have to compile the code myself?
If I need to compile the code, which software is required under Win 8.1?
Thanks again!

**Comment by rtitlestad** [comment] 2015-01-07 05:15
Someone did attach an APK to one of the comments on [this issue](https://code.google.com/p/google-authenticator/issues/detail?id=396) otherwise you can [install Android Studio](http://developer.android.com/sdk/installing/index.html?pkg=studio) if you want to compile it yourself.

**Comment by MarMuc** [comment] 2015-01-07 08:28
I downloaded the compiled issue from the other post and it solved my problem. Great!
Thanks very much!
Best regards

**Comment by ThomasHabets** [comment] 2015-01-07 10:35
Sounds fixed then.

**Closed by ThomasHabets** 2015-01-07 10:35 UTC

**Comment by erw2** [comment] 2015-03-27 15:03
Hello, as I am facing a similar or perhaps the same problem here on a Mobistel Cynus T6, I would like to ask for the compiled version, too (as the other post is no longer locatable).
I'd really like to give it a try with the compiled apk as I'm used to use the Authenticator very frequently.
Would it be possibly to provide a download linke, please?
Thanks in advance.

**Comment by ThomasHabets** [comment] 2015-03-27 16:55
Unfortunately I had to lock down the project on code.google.com because people kept opening bugs there. I've built a new APK at the current version, and it seems that I have to create a release in order to upload APKs to github.

Try downloading the apk from this "release":
https://github.com/google/google-authenticator-android/releases/tag/test-do-not-package

Disclaimer: This is not an actual release. I just built HEAD, which has this bugfix.

**Comment by erw2** [comment] 2015-03-27 17:43
Hello, and thank you for supplying the link to the built apk.

Too bad it did not help - the apk did not install (and of course I did
enable "install from unknow locations").
Trying to install the downloaded apk simply quits with "App not installed."
without any hint why it did not.

Sorry to bother you, but: any clues why this apk does not install?

2015-03-27 17:55 GMT+01:00 Thomas Habets <notifications@github.com>:

**Comment by ThomasHabets** [comment] 2015-03-30 10:25
Don't know. I built with version 21 of the SDK. Maybe your phone wanted an older version.

I don't have any older version, but have copied the binary from the closed code.google.com project here:
https://github.com/google/google-authenticator-android/releases/tag/test-do-not-package-this-either

USE AT YOUR OWN RISK.

**Comment by capi** [comment] 2015-03-30 13:13
@erw2 Do you have the Play-Store version installed? It has the same package name but of course a different signature than the provided APK, so you could not have them installed both at the same time.

**Comment by erw2** [comment] 2015-03-30 13:21
Hello, thanks to Thomas for supplying another version. Will test this evening.

@capi: Yes, I had the PlayStore version installed (and running, but not working - as described before).
But before trying to install the provided apk I did uninstall the PlayStore version - and reboot the phone.

Will post feedback in a few hours. Thanks again.

**Comment by erw2** [comment] 2015-03-31 05:00
Thanks again - the 2nd apk did work perfectly, good to be able to use the Authenticator again.

NB: the 1st apk did not work on a 2nd phone, too (an Acer Liquid E700), but there it was just for testing. On this platform the PlayStore Version is working fine.

Perhaps to help other users, a list of phones should be provided that need this tmp fix to have GAuth working:

- Wiko Highway Signs, Android 4.4.2
- mobistel Cynus T6, Android 4.4.2 with Kernel 3.4.67

**Comment by ThomasHabets** [comment] 2015-03-31 07:45
Great!

The play store version will be fixed with the next release. No ETA on when that release is going to happen.

**Comment by mithro** [comment] 2015-05-03 15:37
This problem also seems to affect the ZTE Blade Vec 3G (which runs Android 4.4.2 KitKat). I've confirmed the custom built APK above fixes the problem.

**Comment by ThomasHabets** [comment] 2015-12-13 14:52
Sorry for the delay. By now the new version of the closed source GA app should certainly have been released, with this fix in place. The newest version seems to have a white background, so if you have a white background then this issue should be fixed for you.

**Comment by MChelik** [comment] 2016-08-07 20:02
I have same problem too. I enable my GitLab's 2-step authentication, shows me a QR code, I scan it with Google Authenticator App and adds it as new account but when I enter its produced codes to my GitLab account, website says "PIN incorrect". My phone's date and time settings are correct. It worked for my Gmail account but fails at GitLab account. How can I solve this problem? Do you have any idea?

**Comment by ThomasHabets** [comment] 2016-08-08 08:15
@MChelik what version of the app? The open source version or the closed source version?

**Comment by MChelik** [comment] 2016-08-08 09:07
4.6 of closed source Google Authenticator. Sorry, I think I commented at wrong place. Thank you anyway Thomas.

**Comment by MChelik** [comment] 2016-08-08 09:09
4.6 of closed source Google Authenticator. Sorry, I think I commented at wrong place. Thank you anyway Thomas.

**Comment by ThomasHabets** [comment] 2016-08-08 12:03
4.6 has the fix mentioned in this bug, so must be another issue. I don't really know how to torubleshoot it, especially since it works for gmail. It could be a GitLab issue.

**Comment by capi** [comment] 2016-08-11 18:37
I checked with my own GitLab instance, Google's and this current open-source version of Authenticator work with GitLab, so it's not a general GitLab/Authenticator issue, but must be related somehow to the reporter's phone.

**Comment by MChelik** [comment] 2016-08-11 21:11
I created new access token on my GitLab account and it worked. I just wanted to share my solution. Thanks.

**Comment by syedhaider123** [comment] 2017-01-17 11:02
Hi guyz,

Hope you all sound good , could you guyz help me out , my google authenticator app old generated pin are still validating though new one generated  why is that ?

Note: I have explicitly delayed time span to 1 hour for validating two factor

**Comment by zamronypj** [comment] 2017-12-14 03:20
I had similar problem of invalid code when re-enabling 2FA on gitlab. @ThomasHabets comment pointed me to right direction. It was clock-synced related problem. Date time setting on my device was set manually while my computer was set automatically. When I changed my device date time setting to automatic, problem was solved.

**Comment by panaeolia** [comment] 2018-06-01 15:28
@ThomasHabets can u help me ,i have same problem 
i use android 4.4.1 ,i cant get my app synced
date/time is ok even
itried automatic time same problem

**Comment by MChelik** [comment] 2018-06-01 15:38
@panaeolia go to settings and click on time correction. it will solve it

**Comment by panaeolia** [comment] 2018-06-01 15:40
mate as im saying all those didnt work for me i get error google servers

**Comment by panaeolia** [comment] 2018-06-01 15:42
let me tell all the story....i accidentaly remove battery without turn off the phone
when i plug it ,time and day ,messed so when i correct em back g.auth app destroyed

**Comment by MChelik** [comment] 2018-06-01 15:58
Hmm... so make sure your device's time and timezone is set correctly. Wrong case scenario: remove all accounts and create new ones with your backup codes

**Comment by ThomasHabets** [comment] 2018-06-01 21:11
locking because comments are getting off-topic.
